### ISSUE TITLE
Numerous cannot find victim warnings in IntelliJ log

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#269]
Just upgraded from version 4.31.0 to 4.32.1 and I am noticing a number of ```[  14752]   WARN - hecker.CheckStyleAuditListener - Couldn't find victim for error: ...``` warnings in the IntelliJ log. These were for Tab characters in the file. I assume that this is because a line could not be identified for the issue. I see the error displayed at the top of the file as expected. Since everything is functioning as intended, why put a warning in the log. In a project with numerous victimless crimes, this will spam the log and there does not appear to be anything that the developer can or should do to avoid these. Please consider changing these log messages to DEBUG level.

Thanks!

**Comment by jshiell** [comment]
Thanks for the feedback.

This case has always existed - the new version includes a change to display these at the top of the file, however, rather than just log them. One possible cause is that the editor tab size doesn't match that configured in the rules file (which throws all of the line indexing off), which was also fixed in the latest release.

Nevertheless, your suggestion is a good one - I'll switch it next time I do a release.

**Comment by baron1405** [comment]
Thanks for the quick reply and for considering the logging change. I will check my configuration file tab settings. That would certainly explain why I am just noticing the warning.

Cheers,
Baron

**Comment by jshiell** [comment]
I might actually also change the default tab size - it falls back to eight if not set from memory, which is the CS default, but IDEA defaults to four. Seems sensible to default to match IDEA in the circumstances.

**Comment by baron1405** [comment]
Agree that conforming to IDEA's setting is advisable.

I added the tabWidth property to TreeWalker and the issue highlights are closer to the actual location of the issue. However, I am still getting victim warnings.

**Comment by baron1405** [comment]
Sorry it took me a while to get back to checking this, but I am happy to report that the changes make for a quieter logging experience. Thanks!

**Comment by jshiell** [comment]
Thanks for the feedback, and your help!
