### ISSUE TITLE
Realtime error highlighting problematic on Windows

### ISSUE THREAD

**Issue by embee1981** [jshiell/checkstyle-idea#302]
When using Windows the realtime error highlighting doesn't seem to work. 

Debugging through the code it seems that the code that is handling paths is not Windows friendly (or at least the Java API is giving different results from Linux/Mac that need handled in a special windows way ;-). 

```
CommonUtils.relativizeAndNormalizePath("C:\Users\Mark\IdeaProjects\myProj" , "C:\Users\Mark\AppData\Local\Temp\csi-c5c731b7-6fcb-475a-926b-d55e8545b8e5\java\SomeFile.java") 
```
returns

```
..\..\AppData\Local\Temp\csi-c5c731b7-6fcb-475a-926b-d55e8545b8e5\java\SomeFile.java
```

Later on when the code hits ```ProcessResultsThread's run()``` method the following returns null

```
final PsiFile psiFile = fileNamesToPsiFiles.get(filenameFrom(event))
```
as ```fileNamesToPsiFiles``` contains ```"C:\Users\Mark\AppData\Local\Temp\csi-c5c731b7-6fcb-475a-926b-d55e8545b8e5\java\SomeFile.java" -> "PsiJavaFile:SomeFile.java"``` while ```filenameFrom(event)``` returns ```C:\Users\Mark\IdeaProjects\myproj\..\..\AppData\Local\Temp\csi-dbbb6c81-95dc-4f7f-978e-87656618018c\java\SomeFile.java```

The Java NIO ```relativize``` method also has problems when the source code lives on a different drive from where the Windows temp drive is. My code is typically on drive E while Windows temp is on C. This throws an exception - ```java.lang.IllegalArgumentException: 'other' has different root``` ceasing the checking and causing the config file to be blacklisted for a while :-(

Keep up the good work with the plugin :-D

Versions
Checkstyle plugin version : 5.3.0
Checkstyle version : 7.6.1
Intellij version : 2017.1
Windows 10
Java 1.8.0_121

**Comment by jshiell** [comment]
Thanks for the most excellent bug report! I can't guarantee anything solid, given I don't have a Windows machine, but you've given some really good hints here so I'll certainly see what I can do. If I can build tests off the above - which seems a good bet given the detail you've given - I can hopefully make progress even without a Win64 box.

**Comment by jshiell** [comment]
I don't suppose you have a stack trace for the `IllegalArgumentException` where different drive letters are concerned?

On the first problem, I've added some path normalisation after we resolve the event path to the base path. I *think* it'll work, but am unsure - the Java `Paths` implementation seems to be platform specific, so I've no concrete idea on how it'll behave on Windows. But there certainly was a hole around here which is plugged.

I've uploaded a test version [to Dropbox](https://www.dropbox.com/s/zbzlij1fn3fn2zh/CheckStyle-IDEA-5.3.1.zip?dl=0) - if you're able to give it a try, that would be most helpful. Thank you!

**Comment by embee1981** [comment]
Stack trace below :-)
Parameter values for the call to relativize() are

pathBase == ```e:\IdeaProjects\MyTestProject```
pathAbsolute == ```C:\Users\Mark\AppData\Local\Temp\csi-f59c5db5-5e11-4084-9a48-34ea5f39e5ca\java\com\blah\Foobar.java```

Pretty useless exception message by the java code unfortunately 

```
java.lang.IllegalArgumentException: 'other' has different root
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.relativizeAndNormalizePath(CommonUtils.java:257)
	at com.puppycrawl.tools.checkstyle.Checker.acceptFileStarted(Checker.java:346)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:277)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:75)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:121)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:67)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$1(CheckStyleInspection.java:92)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:92)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:357)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Will test the new version shortly :-)

**Comment by embee1981** [comment]
Yep that does the trick for the first issue :-D

**Comment by jshiell** [comment]
There's now a prospective fix (hack?) in 5.4.0, which, if the OS is Windows, attempts to verify if the system tmp directory is on the same disk as the file. If not, it'll try to create a temporary folder in the project directory and use this.

I say prospective as I had no luck in building unit tests for this - I'd need to either manage to bend the Jetbrains mock project to my will (where I had no luck) or refactor the code to pull out the IDEA API singletons in play (which would be a good thing really). So it's an informed guess.

Assuming all works well, I'd expect I'll have to do some work to get it to clean up after itself a bit better. Ideally we'd move the temp folder into the `build`/`target` directory, so as to avoid VCS problems. But first things first - if it works, please let me know and I'll try refine it. If not, guess I'll have to think harder. Thanks!

**Comment by embee1981** [comment]
Hey thanks for continuing to look at this :-)
Unfortunately its till having issues with the path relativize stuff looks like it the checkstyle code using the module path this time

Stacktrace below
```
java.lang.IllegalArgumentException: 'other' has different root
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.relativizeAndNormalizePath(CommonUtils.java:264)
	at com.puppycrawl.tools.checkstyle.Checker.acceptFileStarted(Checker.java:346)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:277)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:75)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:121)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:67)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$1(CheckStyleInspection.java:92)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:92)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:357)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Screenshot of the code at the point where it blows up which shows the paths in play

![stack](https://cloud.githubusercontent.com/assets/13723136/25776108/e53ac2f0-32ac-11e7-8a9f-6f68bf8325b2.jpg)

**Comment by jshiell** [comment]
Hmm. I presume `A.java` is on `E:\`? That implies my 'fix' isn't working at all, as it was supposed to ensure a temp file wouldn't be created if the drive of the file differed from the drive of the temp directory.

If `A.java` is on `C:\` that makes this more interesting, but I presume it's just my failure on the fix 😄

**Comment by jshiell** [comment]
I've double checked, and `ScannableFile` does appear to be the only place where we create the temporary file, which implies my detection of the case isn't working. I did omit to ensure the path was normalised & absolute before grabbing the drive letter before, which is corrected in 5.5.1. It still doesn't seem entirely satisfactory though.

**Comment by embee1981** [comment]
Ahh still no luck :-( Same exception as before when the realtime scan kicks in.

The temp file is on c:\ however it looks like
```
acceptFileStarted:346, Checker (com.puppycrawl.tools.checkstyle)
```
the Checker is using for the ```baseDir``` instance variable ```E:\MyProject\.idea\modules``` while the ```fileName``` parameter is ```C:\Users\Mark\AppData\Local\Temp\csi-271b2b96-3326-485d-9293-d04c9a4b9e36\java\SomeClass.java``` which causes the normalization fail :-(

**Comment by jshiell** [comment]
Well, I finally bit the bullet and tracked down a Windows box, and tried to reproduce this, with a project on `D:`. And here's the odd news - it works for me. Odder, it works without the fix.

With the fix, it does trigger the conditional and creates a temp dir in the project directory. Without it, it uses the standard temp dir and works anyway.

Debugging further, I couldn't actually get it to trigger the `CommonUtils` path code, so either the debugger is being a little odd, or there's something more specific to your ruleset in play.

Are you able to attach your rules file, and ideally the file you're using to test? (I assume it's a test file, given the name `AA.java` :smile:)

Thanks very much!

**Comment by embee1981** [comment]
Hey, hope you are having fun with Windows :-D

I've played around a bit more and it seems to now be working sometime for me but then it will blacklist the rules at random. It does seem to be happy with the inbuilt rule list. I've noticed as well that sometimes when I run the on demand scanner it reports there are no errors at all when using my file, very weird.

I'm using intellij 2017.1.3, windows 10 64bit, java 1.8.0_121 64 bit, checkstyle 7.7.  The checkstyle plugin settings are pointing to a file on E drive, same drive as the project. No value specified for basedir.

Attached is the checkstyle file (renamed as .txt) and my super awesome AA class (also renamed as .txt).
[checkstyle-main.txt](https://github.com/jshiell/checkstyle-idea/files/1033803/checkstyle-main.txt)
[AA.txt](https://github.com/jshiell/checkstyle-idea/files/1033804/AA.txt)

**Comment by jshiell** [comment]
How you cope with the font rendering on Windows I'll never know. And I had to install Git myself! ;-)

The good news is that with your finely crafted files (thank you!) I've been able to reproduce it. And it suggests I'm an idiot - when I checked we could create the project temporary directory, I failed to check if the directory already existed. Hence it being inconsistent - it worked if the directory didn't exist, and didn't if it had already been created. I've put in a fix for that and will push it out a bit later when I'm back on my workstation.

Fingers crossed for sixth time lucky! :smile:

**Comment by jshiell** [comment]
Released in 5.6.0 - let's hope this works a little more consistently!

**Comment by embee1981** [comment]
Awesome work :-) All good now, thanks for all your hard work :-D

**Comment by jshiell** [comment]
Smashing 😄 Although I did introduced #313 ... let's see if I can fix that without breaking this - thanks for all your help!
